### PR TITLE
Remove encourage-bot

### PR DESCRIPTION
**Pull request by mgwalker**
Please feel free to comment below.

### CODE REVIEW

**Comment by nkkl** [comment]
Casting my vote as a person for whom the bot posts ring hollow.

**Comment by melchoyce** [comment]
Yeah when I first encountered this bot it felt weird and uncomfortable to me. I'm glad it hasn't pinged me yet.

**Comment by hartsick** [comment]
I've left #random because I don't know of a way to opt-out of the bot. I think it rings hollow and I don't like the attention it brings. I'd be interested in having a message from it be opt-in, have an option to opt-out, or be removed from the channel

**Comment by bklaas** [comment]
Another vote for encourage-bot removal. I like giving kudos to people, but I'm not a fan of bots giving kudos to people.

**Comment by sawtoothwave** [comment]
I appreciate the thoughtful intent behind the creation of encourage-bot, but it also rings hollow to me/makes me feel weird. Another vote for removal from me; apologies to my bot brethren.

**Review by julialeague — APPROVED** [review]

**Comment by bklaas** [comment]
@mgwalker just occurred to me that encourage-bot should also be removed from README.md

**Pull request merged**
